name: CI/CD

on: push

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CI: true
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Use Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Install NPM dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          path: dist/bluedot-keycloak-theme.jar

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/bluedot-keycloak-theme.jar